#!/bin/bash

state='.lpass'

if [ ! -d ~/${state} ]
then
  mkdir ~/${state}
fi

docker run --rm -it \
           --name lastpass-cli \
           --volume ~/${state}:/home/lpass/${state} \
           cagiti/lastpass-cli:latest $*
